In [201]:
import numpy as np
import matplotlib.pyplot as pl
import pandas as pd

Training Data

In [202]:
training_data = np.loadtxt('trainingdataset.txt', usecols=(), skiprows=0, delimiter=',')
x_training = training_data[:, :-1]
y_training = training_data[:, -1]
#print('number of samples in Y training data = ' + np.str(y_training.shape[0]))
#print (y_training.shape[0])
#print( 'This is the Xtraining data shape = ' + np.str(x_training.shape[0]))
#print (x_training)
y_training[y_training==2]=0

In [203]:
testing_data = np.loadtxt('testingdataset.txt', usecols=(), skiprows=0, delimiter=',')
x_testing = testing_data[:, :-1]
y_testing = testing_data[:, -1]
y_testing[y_testing==2]=0

In [204]:
def KNN(x, y, x_q, K=3):
    target_labels = np.unique(y) # unique set of target labels
    target_labels_counts = np.zeros(len(target_labels)) # keeps counts of target labels
    d = np.sqrt(np.sum((x - x_q)**2, axis=1)) # use the Euclidean distance
    i = np.argsort(d) # sort distance vector in ascending order
    for k in np.arange(len(target_labels)):
        target_labels_counts[k] = np.sum(y[i[0:K]]==target_labels[k]) # count the number of each target lable in K Nearest Neighbourhood
    # apply the majority voting
    l = np.argmax(target_labels_counts)
    return target_labels[l]    

In [205]:
N = y_testing.shape[0] # the number of examples in training dataset
print('{:>2} {:>16}'.format('K', 'Testing Error'))
for K in np.arange(1, 33, 2):
    y_prediction = np.zeros(N)
    for n in np.arange(N):
        x_q = x_testing[n]
        print(x_q)
        y_prediction[n] = KNN(x_training, y_training, x_q, K)
    classification_error = np.sum(y_testing != y_prediction) / N
    print('{:>2.0f} {:>16.4f}'.format(K, classification_error))

 K    Testing Error
[57. 67.  0.]
[58. 59.  0.]
[58. 60.  3.]
[58. 61.  1.]
[58. 67.  0.]
[58. 58.  0.]
[58. 58.  3.]
[58. 61.  2.]
[59. 62. 35.]
[59. 60.  0.]
[59. 63.  0.]
[59. 64.  1.]
[59. 64.  4.]
[59. 64.  0.]
[59. 64.  7.]
[59. 67.  3.]
[60. 59. 17.]
[60. 65.  0.]
[60. 61.  1.]
[60. 67.  2.]
[60. 61. 25.]
[60. 64.  0.]
[61. 62.  5.]
[61. 65.  0.]
[61. 68.  1.]
[61. 59.  0.]
[61. 59.  0.]
[61. 64.  0.]
[61. 65.  8.]
[61. 68.  0.]
[61. 59.  0.]
[62. 59. 13.]
[62. 58.  0.]
[62. 65. 19.]
[62. 62.  6.]
[62. 66.  0.]
[62. 66.  0.]
[62. 58.  0.]
[63. 60.  1.]
[63. 61.  0.]
[63. 62.  0.]
[63. 63.  0.]
[63. 63.  0.]
[63. 66.  0.]
[63. 61.  9.]
[63. 61. 28.]
[64. 58.  0.]
[64. 65. 22.]
[64. 66.  0.]
[64. 61.  0.]
[64. 68.  0.]
[65. 58.  0.]
[65. 61.  2.]
[65. 62. 22.]
[65. 66. 15.]
[65. 58.  0.]
[65. 64.  0.]
[65. 67.  0.]
[65. 59.  2.]
[65. 64.  0.]
[65. 67.  1.]
[66. 58.  0.]
[66. 61. 13.]
[66. 58.  0.]
[66. 58.  1.]
[66. 68.  0.]
[67. 64.  8.]
[67. 63.  1.]
[67. 66.  0.]
[67. 66.  0.]


[66. 58.  1.]
[66. 68.  0.]
[67. 64.  8.]
[67. 63.  1.]
[67. 66.  0.]
[67. 66.  0.]
[67. 61.  0.]
[67. 65.  0.]
[68. 67.  0.]
[68. 68.  0.]
[69. 67.  8.]
[69. 60.  0.]
[69. 65.  0.]
[69. 66.  0.]
[70. 58.  0.]
[70. 58.  4.]
[70. 66. 14.]
[70. 67.  0.]
[70. 68.  0.]
[70. 59.  8.]
[70. 63.  0.]
[71. 68.  2.]
[72. 63.  0.]
[72. 58.  0.]
[72. 64.  0.]
[72. 67.  3.]
[73. 62.  0.]
[73. 68.  0.]
[74. 65.  3.]
[74. 63.  0.]
[75. 62.  1.]
[76. 67.  0.]
[77. 65.  3.]
[78. 65.  1.]
[83. 58.  2.]
[57. 64.  0.]
17           0.2500
[57. 67.  0.]
[58. 59.  0.]
[58. 60.  3.]
[58. 61.  1.]
[58. 67.  0.]
[58. 58.  0.]
[58. 58.  3.]
[58. 61.  2.]
[59. 62. 35.]
[59. 60.  0.]
[59. 63.  0.]
[59. 64.  1.]
[59. 64.  4.]
[59. 64.  0.]
[59. 64.  7.]
[59. 67.  3.]
[60. 59. 17.]
[60. 65.  0.]
[60. 61.  1.]
[60. 67.  2.]
[60. 61. 25.]
[60. 64.  0.]
[61. 62.  5.]
[61. 65.  0.]
[61. 68.  1.]
[61. 59.  0.]
[61. 59.  0.]
[61. 64.  0.]
[61. 65.  8.]
[61. 68.  0.]
[61. 59.  0.]
[62. 59. 13.]
[62. 58.  0.]
[62. 65. 19.]


In [206]:
classification_error

0.21

In [207]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifier.fit(x_training, y_training)

# Predicting the Test set results
y_pred = classifier.predict(x_testing)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_testing, y_pred)
cm

array([[12, 13],
       [12, 63]], dtype=int64)

In [208]:
x_training

array([[30., 64.,  1.],
       [30., 62.,  3.],
       [30., 65.,  0.],
       [31., 59.,  2.],
       [31., 65.,  4.],
       [33., 58., 10.],
       [33., 60.,  0.],
       [34., 59.,  0.],
       [34., 66.,  9.],
       [34., 58., 30.],
       [34., 60.,  1.],
       [34., 61., 10.],
       [34., 67.,  7.],
       [34., 60.,  0.],
       [35., 64., 13.],
       [35., 63.,  0.],
       [36., 60.,  1.],
       [36., 69.,  0.],
       [37., 60.,  0.],
       [37., 63.,  0.],
       [37., 58.,  0.],
       [37., 59.,  6.],
       [37., 60., 15.],
       [37., 63.,  0.],
       [38., 69., 21.],
       [38., 59.,  2.],
       [38., 60.,  0.],
       [38., 60.,  0.],
       [38., 62.,  3.],
       [38., 64.,  1.],
       [38., 66.,  0.],
       [38., 66., 11.],
       [38., 60.,  1.],
       [38., 67.,  5.],
       [39., 66.,  0.],
       [39., 63.,  0.],
       [39., 67.,  0.],
       [39., 58.,  0.],
       [39., 59.,  2.],
       [39., 63.,  4.],
       [40., 58.,  2.],
       [40., 58.

In [209]:
x_testing

array([[57., 67.,  0.],
       [58., 59.,  0.],
       [58., 60.,  3.],
       [58., 61.,  1.],
       [58., 67.,  0.],
       [58., 58.,  0.],
       [58., 58.,  3.],
       [58., 61.,  2.],
       [59., 62., 35.],
       [59., 60.,  0.],
       [59., 63.,  0.],
       [59., 64.,  1.],
       [59., 64.,  4.],
       [59., 64.,  0.],
       [59., 64.,  7.],
       [59., 67.,  3.],
       [60., 59., 17.],
       [60., 65.,  0.],
       [60., 61.,  1.],
       [60., 67.,  2.],
       [60., 61., 25.],
       [60., 64.,  0.],
       [61., 62.,  5.],
       [61., 65.,  0.],
       [61., 68.,  1.],
       [61., 59.,  0.],
       [61., 59.,  0.],
       [61., 64.,  0.],
       [61., 65.,  8.],
       [61., 68.,  0.],
       [61., 59.,  0.],
       [62., 59., 13.],
       [62., 58.,  0.],
       [62., 65., 19.],
       [62., 62.,  6.],
       [62., 66.,  0.],
       [62., 66.,  0.],
       [62., 58.,  0.],
       [63., 60.,  1.],
       [63., 61.,  0.],
       [63., 62.,  0.],
       [63., 63.

Testing Data

In [210]:
#testing_data = np.loadtxt('testingdataset.txt', usecols=(), skiprows=0, delimiter=',')
#x_testing = testing_data[:, :-1]
#y_testing = testing_data[:, -1]
#print('number of samples in testing data = ' + np.str(y_testing.shape[0]))
#print (y_testing.shape [0])
#print('This is the X testing data set =' + np.str(x_testing.shape[0]))
#print (x_testing)
print (y_testing)
#feature_names = {0:'Patients Age', 1:'Year of Operation', 2:'Number of Positive Axillary nodes'}

[1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0.
 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 1.
 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 0. 1.]


In [211]:
x_training

array([[30., 64.,  1.],
       [30., 62.,  3.],
       [30., 65.,  0.],
       [31., 59.,  2.],
       [31., 65.,  4.],
       [33., 58., 10.],
       [33., 60.,  0.],
       [34., 59.,  0.],
       [34., 66.,  9.],
       [34., 58., 30.],
       [34., 60.,  1.],
       [34., 61., 10.],
       [34., 67.,  7.],
       [34., 60.,  0.],
       [35., 64., 13.],
       [35., 63.,  0.],
       [36., 60.,  1.],
       [36., 69.,  0.],
       [37., 60.,  0.],
       [37., 63.,  0.],
       [37., 58.,  0.],
       [37., 59.,  6.],
       [37., 60., 15.],
       [37., 63.,  0.],
       [38., 69., 21.],
       [38., 59.,  2.],
       [38., 60.,  0.],
       [38., 60.,  0.],
       [38., 62.,  3.],
       [38., 64.,  1.],
       [38., 66.,  0.],
       [38., 66., 11.],
       [38., 60.,  1.],
       [38., 67.,  5.],
       [39., 66.,  0.],
       [39., 63.,  0.],
       [39., 67.,  0.],
       [39., 58.,  0.],
       [39., 59.,  2.],
       [39., 63.,  4.],
       [40., 58.,  2.],
       [40., 58.

In [212]:
y_training[y_training==2]=0


#[Pat==0]=2
y_training

array([1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1.])

In [213]:
class LogReg:
    def __init__(self, W):
        self.W = W
        self.delta = 0.00012 #change in error not to be exceeded
        self.epoch_max = 100000
        
    def parameters(self):
        return self.W
    
    def activation(self, s):
        #return 2.0 / (1 + np.exp(-2*s))-1 #between [-1,1]# sigmoid function as activation function
        return 1.0 / (1 + np.exp(-s))#[0,1]
    def activation_prime(self, s):
        return (self.activation(s) * (1.0 - self.activation(s))) # the derivative of activation function
    
    def feedforward(self, X):
        S = np.dot(X, self.W)
        U = self.activation(S)
        return (U)        
        
    def learn(self, X, Y, learning_rate):        
        C =  len(np.unique(Y))
        N = X.shape[0]
        #Yv = np.zeros((N, C))
        #Yv[np.arange(N), Y.astype(np.int)] = 1.0
        is_converged = False
        epoch = 1
        while not is_converged:
            U = self.feedforward(X)
            E = (U - Y)
            #print(E.shape)
            #print("asd ",np.dot(E, np.dot(U.T, (1-U))).shape)
            D = E * (U * (1-U))
            MSE = 1.0 / (2 * N) * np.sum(np.sum(E**2, axis=1))
            if (epoch%100) == 0:
                ACC = self.accuracy(X, np.asarray(pd.DataFrame(Y)[0]))
                print('epoch = {0}, MSE = {1:.3f}, ACC = {2:.3f}'.format(epoch, MSE, ACC))
            Wprev = self.W.copy()
            self.W = self.W - learning_rate * 1.0/N * np.dot(X.T, D)
            epoch += 1
            if (epoch >=self.epoch_max):
                is_converged = True 
        return self.W
        
    def classify(self, X):
        U = self.feedforward(X)
        L = []
        import pandas as pd
        for x in pd.DataFrame(U)[0].tolist():
            if(x >= 0.5):
                L.append(1);
            else:
                L.append(0);
        return pd.Series(L)
    
    def accuracy(self, X, Y):
        N = X.shape[0]
        L = self.classify(X)
        acc = np.sum(L == Y) / N
        return acc
    
    def confusion_matrix(self, X, Y):
        L = self.accuracy(X, Y)
        labels = np.unique(Y).astype(int)
        conf_mat = np.zeros((len(labels), len(labels)))
        for i in np.arange(len(labels)):
            for j in np.arange(len(labels)):
                conf_mat[i, j] = np.sum((L==labels[i]) and (Y==labels[j]))

In [214]:
W = np.random.randn(4, 1)
print(W.shape)
#W = np.hstack((np.ones((W.shape[0],1)), W))
LR = LogReg(W)
LR.learn(np.hstack((np.ones((x_training.shape[0],1)),x_training)),np.asarray([y_training]).T,1.0)
x_testing = np.hstack((np.ones((x_testing.shape[0],1)),x_testing))
y_pred = LR.classify(x_testing)

display("Correctly predicted:",len(y_pred[y_pred == y_testing]))
display("Total:",len(y_testing))

(4, 1)
epoch = 100, MSE = 0.136, ACC = 0.728
epoch = 200, MSE = 0.136, ACC = 0.728
epoch = 300, MSE = 0.136, ACC = 0.728
epoch = 400, MSE = 0.136, ACC = 0.728
epoch = 500, MSE = 0.136, ACC = 0.728
epoch = 600, MSE = 0.136, ACC = 0.728
epoch = 700, MSE = 0.136, ACC = 0.728
epoch = 800, MSE = 0.136, ACC = 0.728
epoch = 900, MSE = 0.136, ACC = 0.728
epoch = 1000, MSE = 0.136, ACC = 0.728
epoch = 1100, MSE = 0.136, ACC = 0.728
epoch = 1200, MSE = 0.136, ACC = 0.728
epoch = 1300, MSE = 0.136, ACC = 0.728
epoch = 1400, MSE = 0.136, ACC = 0.728
epoch = 1500, MSE = 0.136, ACC = 0.728
epoch = 1600, MSE = 0.136, ACC = 0.728
epoch = 1700, MSE = 0.136, ACC = 0.728
epoch = 1800, MSE = 0.136, ACC = 0.728
epoch = 1900, MSE = 0.136, ACC = 0.728
epoch = 2000, MSE = 0.136, ACC = 0.728
epoch = 2100, MSE = 0.136, ACC = 0.728
epoch = 2200, MSE = 0.136, ACC = 0.728
epoch = 2300, MSE = 0.136, ACC = 0.728
epoch = 2400, MSE = 0.136, ACC = 0.728
epoch = 2500, MSE = 0.136, ACC = 0.728
epoch = 2600, MSE = 0.136, 

epoch = 21200, MSE = 0.136, ACC = 0.728
epoch = 21300, MSE = 0.136, ACC = 0.728
epoch = 21400, MSE = 0.136, ACC = 0.728
epoch = 21500, MSE = 0.136, ACC = 0.728
epoch = 21600, MSE = 0.136, ACC = 0.728
epoch = 21700, MSE = 0.136, ACC = 0.728
epoch = 21800, MSE = 0.136, ACC = 0.728
epoch = 21900, MSE = 0.136, ACC = 0.728
epoch = 22000, MSE = 0.136, ACC = 0.728
epoch = 22100, MSE = 0.136, ACC = 0.728
epoch = 22200, MSE = 0.136, ACC = 0.728
epoch = 22300, MSE = 0.136, ACC = 0.728
epoch = 22400, MSE = 0.136, ACC = 0.728
epoch = 22500, MSE = 0.136, ACC = 0.728
epoch = 22600, MSE = 0.136, ACC = 0.728
epoch = 22700, MSE = 0.136, ACC = 0.728
epoch = 22800, MSE = 0.136, ACC = 0.728
epoch = 22900, MSE = 0.136, ACC = 0.728
epoch = 23000, MSE = 0.136, ACC = 0.728
epoch = 23100, MSE = 0.136, ACC = 0.728
epoch = 23200, MSE = 0.136, ACC = 0.728
epoch = 23300, MSE = 0.136, ACC = 0.728
epoch = 23400, MSE = 0.136, ACC = 0.728
epoch = 23500, MSE = 0.136, ACC = 0.728
epoch = 23600, MSE = 0.136, ACC = 0.728


epoch = 43200, MSE = 0.136, ACC = 0.728
epoch = 43300, MSE = 0.136, ACC = 0.728
epoch = 43400, MSE = 0.136, ACC = 0.728
epoch = 43500, MSE = 0.136, ACC = 0.728
epoch = 43600, MSE = 0.136, ACC = 0.728
epoch = 43700, MSE = 0.136, ACC = 0.728
epoch = 43800, MSE = 0.136, ACC = 0.728
epoch = 43900, MSE = 0.136, ACC = 0.728
epoch = 44000, MSE = 0.136, ACC = 0.728
epoch = 44100, MSE = 0.136, ACC = 0.728
epoch = 44200, MSE = 0.136, ACC = 0.728
epoch = 44300, MSE = 0.136, ACC = 0.728
epoch = 44400, MSE = 0.136, ACC = 0.728
epoch = 44500, MSE = 0.136, ACC = 0.728
epoch = 44600, MSE = 0.136, ACC = 0.728
epoch = 44700, MSE = 0.136, ACC = 0.728
epoch = 44800, MSE = 0.136, ACC = 0.728
epoch = 44900, MSE = 0.136, ACC = 0.728
epoch = 45000, MSE = 0.136, ACC = 0.728
epoch = 45100, MSE = 0.136, ACC = 0.728
epoch = 45200, MSE = 0.136, ACC = 0.728
epoch = 45300, MSE = 0.136, ACC = 0.728
epoch = 45400, MSE = 0.136, ACC = 0.728
epoch = 45500, MSE = 0.136, ACC = 0.728
epoch = 45600, MSE = 0.136, ACC = 0.728


epoch = 64000, MSE = 0.136, ACC = 0.728
epoch = 64100, MSE = 0.136, ACC = 0.728
epoch = 64200, MSE = 0.136, ACC = 0.728
epoch = 64300, MSE = 0.136, ACC = 0.728
epoch = 64400, MSE = 0.136, ACC = 0.728
epoch = 64500, MSE = 0.136, ACC = 0.728
epoch = 64600, MSE = 0.136, ACC = 0.728
epoch = 64700, MSE = 0.136, ACC = 0.728
epoch = 64800, MSE = 0.136, ACC = 0.728
epoch = 64900, MSE = 0.136, ACC = 0.728
epoch = 65000, MSE = 0.136, ACC = 0.728
epoch = 65100, MSE = 0.136, ACC = 0.728
epoch = 65200, MSE = 0.136, ACC = 0.728
epoch = 65300, MSE = 0.136, ACC = 0.728
epoch = 65400, MSE = 0.136, ACC = 0.728
epoch = 65500, MSE = 0.136, ACC = 0.728
epoch = 65600, MSE = 0.136, ACC = 0.728
epoch = 65700, MSE = 0.136, ACC = 0.728
epoch = 65800, MSE = 0.136, ACC = 0.728
epoch = 65900, MSE = 0.136, ACC = 0.728
epoch = 66000, MSE = 0.136, ACC = 0.728
epoch = 66100, MSE = 0.136, ACC = 0.728
epoch = 66200, MSE = 0.136, ACC = 0.728
epoch = 66300, MSE = 0.136, ACC = 0.728
epoch = 66400, MSE = 0.136, ACC = 0.728


epoch = 85500, MSE = 0.136, ACC = 0.728
epoch = 85600, MSE = 0.136, ACC = 0.728
epoch = 85700, MSE = 0.136, ACC = 0.728
epoch = 85800, MSE = 0.136, ACC = 0.728
epoch = 85900, MSE = 0.136, ACC = 0.728
epoch = 86000, MSE = 0.136, ACC = 0.728
epoch = 86100, MSE = 0.136, ACC = 0.728
epoch = 86200, MSE = 0.136, ACC = 0.728
epoch = 86300, MSE = 0.136, ACC = 0.728
epoch = 86400, MSE = 0.136, ACC = 0.728
epoch = 86500, MSE = 0.136, ACC = 0.728
epoch = 86600, MSE = 0.136, ACC = 0.728
epoch = 86700, MSE = 0.136, ACC = 0.728
epoch = 86800, MSE = 0.136, ACC = 0.728
epoch = 86900, MSE = 0.136, ACC = 0.728
epoch = 87000, MSE = 0.136, ACC = 0.728
epoch = 87100, MSE = 0.136, ACC = 0.728
epoch = 87200, MSE = 0.136, ACC = 0.728
epoch = 87300, MSE = 0.136, ACC = 0.728
epoch = 87400, MSE = 0.136, ACC = 0.728
epoch = 87500, MSE = 0.136, ACC = 0.728
epoch = 87600, MSE = 0.136, ACC = 0.728
epoch = 87700, MSE = 0.136, ACC = 0.728
epoch = 87800, MSE = 0.136, ACC = 0.728
epoch = 87900, MSE = 0.136, ACC = 0.728


'Correctly predicted:'

75

'Total:'

100

In [216]:
import pandas as pd
pd.Series(y_training).value_counts()

1.0    150
0.0     56
dtype: int64

In [217]:
x_q = np.array([64.0, 58.0, 7.0])
x_q.shape

(3,)

In [218]:
def normalize_data(x):

    mean_vector = np.mean(x, axis=0)
    mean_vector[0] = 0
    std_vector = np.std(x, axis=0)
    std_vector[0] = 1.0

    x = x - mean_vector
    x = x / std_vector
    return x

In [219]:
knnpredict = []
for point in x_training:
    predicted_label = KNN(x_training, y_training, point, K=19)
    knnpredict.append(predicted_label)
knnpredict = np.asarray(knnpredict)
display("prediction", knnpredict)

'prediction'

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1.])

In [220]:
N = y_training.shape[0] # the number of examples in training dataset
print('{:>2} {:>16}'.format('K', 'Training Error'))
for K in np.arange(1, 25, 2):
    y_prediction = np.zeros(N)
    for n in np.arange(N):
        x_q = x_training[n]
        y_prediction[n] = KNN(x_training, y_training, x_q, K)
    classification_error = np.sum(y_training != y_prediction) / N
    print('{:>2.0f} {:>16.4f}'.format(K, classification_error))

 K   Training Error
 1           0.0146
 3           0.1505
 5           0.1893
 7           0.2039
 9           0.2330
11           0.2136
13           0.2282
15           0.2087
17           0.2282
19           0.2427
21           0.2282
23           0.2330


In [221]:
import pandas as pd
pd.Series(y_testing).value_counts()

1.0    75
0.0    25
dtype: int64